Update and rename test_commit_1 to test_commit_2
hasalfernando/superset pull request #4
Opened 2023-12-02 09:16 UTC by hasalfernando

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2023-12-06 19:04 UTC, main-competitor commented
This looks good really!

2023-12-06 19:08 UTC, main-competitor reviewed
Adding the review comment 1. Maybe this is a change.

2023-12-06 19:09 UTC, main-competitor approved these changes
This looks good to me. Comment 2.

2023-12-06 19:22 UTC, hasalfernando commented
Thanks

2023-12-07 10:38 UTC, main-competitor requested changes

2023-12-07 10:38 UTC, main-competitor commented on test_commit_2
This seems to be nice

2023-12-07 10:39 UTC, main-competitor commented on test_commit_2
But need to clear

2023-12-07 11:43 UTC, hasalfernando commented on test_commit_2
Trying to test the 3rd comment on this PR. Let's see.

2023-12-07 17:04 UTC, main-competitor approved these changes

2023-12-07 17:04 UTC, main-competitor commented on test_commit_2
Yeah looks good can merge.

2023-12-07 17:09 UTC, merged